site:
  title: Общие цели
  start_page: ROOT::index.adoc
  url: https://text.sharedgoals.ru
output:
  dir: ./public
content:
  sources:
  - url: .
    start_path: ru
    branches: HEAD
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    # url: ./ui-bundle.zip
    url: https://gitlab.com/bongiozzo/antora-ui-bongiozzo/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  # supplemental_files:
  # - path: ui.yml
  #   contents: |
  #     static_files:
  #     - .nojekyll
  #     - CNAME
  # - path: .nojekyll
  # - path: CNAME
  #   contents: |
  #     text.sharedgoals.ru
urls: 
  html_extension_style: drop
asciidoc:
  attributes:
    figure-caption!:
    example-caption!:
    page-pagination: ''
    page-toctitle: 'Содержание'
    page-editgittitle: 'Редактировать текст'
    page-searchthedocs: 'Поиск'
    page-navread: 'Читать'
    page-urlpdf: 'book.pdf'
    page-urlepub: 'book.epub'
    page-urladoc: 'book.txt'
    page-navdiscuss: 'Обсуждать'
    page-urldiscuss:  https://t.me/bongiozzo_public
    page-navwrite: 'Писать'
    page-urlwrite:  https://github.com/bongiozzo/whattodo/
    page-navcompanions: 'РазумИЙ'
    page-urldeepwiki:  https://deepwiki.com/bongiozzo/whattodo
    # page-urlperplexity:  https://www.perplexity.ai/spaces/shared-goals-t..MKe7ISMSaS9lc81qstw
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    languages: [ru,en]
runtime:
  cache_dir: ./.cache/antora
