# -----------------
# Метаданные сайта
# -----------------
site_name: 'Общие цели'
site_description: 'Что мне делать? :-) Текст в концепции «Общие Цели»'
site_url: https://text.sharedgoals.ru/ru/
site_author: Serge Polyakov
copyright: Shared Goals, 2020-....

# Интеграция с репозиторием (кнопки Edit/View).
# NOTE: намеренно закреплено за названием default branch.
repo_url: https://github.com/bongiozzo/whattodo
repo_name: bongiozzo/whattodo
edit_uri: blob/master/text/ru/

# -----------------
# Пути и формат URL
# -----------------
docs_dir: text/ru
site_dir: public/ru
use_directory_urls: true

# ---------------------
# Навигация и структура
# ---------------------
nav:
  - 'Вводная':
    - index.md
  - 'Наблюдения':
    - p1-010-happiness.md
    - p1-020-call.md
    - p1-030-time.md
    - p1-040-unhappiness.md
    - p1-050-country.md
  - 'Практика':
    - p2-100-authors.md
    - p2-110-system.md
    - p2-120-school.md
    - p2-130-local.md
    - p2-140-digital.md
    - p2-150-absurd.md
    - p2-155-photo.md
    - p2-160-routine.md
    - p2-170-opensource.md
    - p2-180-sharedgoals.md
    - p2-190-presentation.md
    - p2-200-text.md
    - p2-999-death.md
  - p3-links.md
  - p3-references.md
  - 'РазумИЙ': # TODO REMOVE ИИШНАЯ
    - 'DeepWiki ↗': https://deepwiki.com/bongiozzo/whattodo
    - 'DZhechko ↗': https://dzhechko.github.io/theory-of-wellbeing-analysis/

# ----------------------------------
# Базовая тема оформления (Material)
# ----------------------------------
theme:
  name: material
  logo: img/logo-dark.svg
  favicon: img/favicon.ico
  language: ru
  features:
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
    - search.suggest
    - search.share
    - content.action.view
    - content.action.edit
  font: 
    text: Tahoma, Verdana, sans-serif
  palette:

    # Палитра для авто режима
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Палитра для светлой темы
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Палитра для тёмной темы
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# ------------------------------------
# Расширения формата разметки Markdown
# ------------------------------------
markdown_extensions:
  - tables

  # Python Markdown
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # PyMdown Extensions
  - pymdownx.betterem:
      smart_enable: all
  # /// caption используется для подписей к изображениям
  - pymdownx.blocks.caption
  # /// для форматирования определений терминов и понятий (define)
  - pymdownx.blocks.definition
  # /// определение стандартных и собственных смысловых блоков текста 
  - pymdownx.blocks.admonition:
      types:
        - abstract                # для примеров, анекдотов, притч и т.п.
        - name: note              # для дополнений, комментариев и т.п.
          title: Дополнение       # подпись по умолчанию
        - name: quote             # для цитат
          title: Цитата           # подпись по умолчанию
        - name: situation         # для ситуаций из жизни
          class: tip              # наследует стиль оформления tip
          title: Ситуация         # подпись по умолчанию
        - name: rule              # для правил и принципов
          class: success          # наследует стиль оформления success  
          title: Правило          # подпись по умолчанию 
        - name: music             # для музыкальных вставок
          class: danger           # наследует стиль оформления danger
          title: Музыка           # подпись по умолчанию
  # /// для сворачиваемых блоков с примерами кода (details)
  - pymdownx.blocks.details
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: text/ru/assets
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# -----------------
# Plugins MkDocs
# -----------------
plugins:
  # text-forge plugin for theme overrides and hooks
  - text-forge:
      editor_enabled: true
      nobr_emoticons_enabled: true
      # Данные для EPUB книги
      epub_title: Что мне делать? :-)
      epub_subtitle: Текст в концепции «Общие Цели»
      epub_author: Сергей Поляков
      epub_identifier: https://text.sharedgoals.ru
      epub_publisher: Shared Goals
      epub_rights: "<a href=\"https://text.sharedgoals.ru\">text.sharedgoals.ru</a>"
      # Подпись к дате публикации (source-file.html)
      source_file_published_title: "Опубликовано"

  # Поиск с возможность делиться ссылками на результаты
  - search

  # Отображение дат создания и изменения файлов из git-репозитория
  - git-revision-date-localized:
      enabled: true
      locale: ru_RU
      type: custom
      custom_format: "%d.%m.%Y"
      enable_creation_date: true
      enable_git_follow: true
      fallback_to_build_date: true

  # Отображение авторов изменений файлов
  # Можно закомментировать по началу
  - git-committers:
      repository: bongiozzo/whattodo
      branch: master
      docs_path: text/ru/
      enabled: !ENV ["MKDOCS_GIT_COMMITTERS_ENABLED", true]

extra:

  # Возможность дискуссий на страницах от Giscus
  # Заменить на свою или закомментировать
  giscus:
    repo: bongiozzo/whattodo
    repo_id: R_kgDOKiRfkg
    category: Announcements
    category_id: DIC_kwDOKiRfks4CaUvR

  # Отображение ссылок на свой канал
  # Заменить на свою или закомментировать
  social:
    - icon: fontawesome/brands/telegram
      name: bongiozzo в Telegram
      link: https://t.me/bongiozzo_public

  # Аналитика посещаемости сайта
  # Заменить на свою или закомментировать
  analytics:
    provider: google
    property: G-DD5EPVVX1K

  # Текст для cookie-баннера.
  consent:
    title: Согласие на использование cookie
    description: >- 
      Мы используем cookie для распознавания повторных посещений,
      а также, чтобы понять – находите ли Вы то, что ищете?
      Спасибо, что делаете наш Текст лучше!
